name: capture-the-flag
version: '1.0-SNAPSHOT'
main: nl.grapjeje.captureTheFlag.Main
api-version: '1.21'
authors: [ GrapJeje ]
description: A Capture The Flag Plugin
website: grapjeje.nl

commands:
  test:
    description: Test command
  help:
    description: Disabled
  me:
    description: Disabled
  msg:
    description: Disabled
  teammsg:
    description: Disabled
  tell:
    description: Disabled
  tm:
    description: Disabled
  trigger:
    description: Disabled
  w:
    description: Disabled
