CREATE TABLE ctf_players
(
    id     INT AUTO_INCREMENT PRIMARY KEY,
    uuid   CHAR(36)    NOT NULL UNIQUE,

    kills  INT UNSIGNED NOT NULL DEFAULT 0,
    deaths INT UNSIGNED NOT NULL DEFAULT 0,
    coins DOUBLE NOT NULL DEFAULT 0
);